name: "CI"
on:
  push:
    branches:
      - main
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v20
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.10.0pre20220822_7c3ab57/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm recursive-nix

      - uses: cachix/cachix-action@v10
        with:
          name: zeek
          pushFilter: '(-source$|nixpkgs\.tar\.gz$)'
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build Spicy
        run: nix develop github:GTrunSec/hunting-lab#build --refresh --command just compile
